version: '3.8'

services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-broker
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    command: uvicorn broker:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-publisher
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
      - BROKER_URL=http://message-broker:8000/produce/
    command: uvicorn publisher:app --host 0.0.0.0 --port 8001
    depends_on:
      - broker
    ports:
      - "8001:8001"

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-consumer
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
      - BROKER_URL=http://message-broker:8000
      - TOPIC=tasks
    command: uvicorn consumer:app --host 0.0.0.0 --port 8002
    depends_on:
      - broker
    ports:
      - "8002:8002"
